name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current date
        run: date
