name: Print Current Date DM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current date
        run: |
          echo "Current date is: $(date +%D)"
